/**
 * generated by Xtext 2.16.0
 */
package org.xtext.bmod.scoping;

import org.xtext.bmod.scoping.BmodScopingScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class BmodScopeProvider extends BmodScopingScopeProvider {
}
