/**
 * generated by Xtext 2.16.0
 */
package org.xtext.bmod.bmod;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Area</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.bmod.bmod.Area#getFrom <em>From</em>}</li>
 *   <li>{@link org.xtext.bmod.bmod.Area#getTo <em>To</em>}</li>
 *   <li>{@link org.xtext.bmod.bmod.Area#getWithout <em>Without</em>}</li>
 * </ul>
 *
 * @see org.xtext.bmod.bmod.BmodPackage#getArea()
 * @model
 * @generated
 */
public interface Area extends EObject
{
  /**
   * Returns the value of the '<em><b>From</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>From</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>From</em>' containment reference.
   * @see #setFrom(Coordinate)
   * @see org.xtext.bmod.bmod.BmodPackage#getArea_From()
   * @model containment="true"
   * @generated
   */
  Coordinate getFrom();

  /**
   * Sets the value of the '{@link org.xtext.bmod.bmod.Area#getFrom <em>From</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>From</em>' containment reference.
   * @see #getFrom()
   * @generated
   */
  void setFrom(Coordinate value);

  /**
   * Returns the value of the '<em><b>To</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>To</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>To</em>' containment reference.
   * @see #setTo(Coordinate)
   * @see org.xtext.bmod.bmod.BmodPackage#getArea_To()
   * @model containment="true"
   * @generated
   */
  Coordinate getTo();

  /**
   * Sets the value of the '{@link org.xtext.bmod.bmod.Area#getTo <em>To</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>To</em>' containment reference.
   * @see #getTo()
   * @generated
   */
  void setTo(Coordinate value);

  /**
   * Returns the value of the '<em><b>Without</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.bmod.bmod.Coordinate}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Without</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Without</em>' containment reference list.
   * @see org.xtext.bmod.bmod.BmodPackage#getArea_Without()
   * @model containment="true"
   * @generated
   */
  EList<Coordinate> getWithout();

} // Area
