/**
 * generated by Xtext 2.16.0
 */
package org.xtext.bmod.bmod;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.bmod.bmod.BmodFactory
 * @model kind="package"
 * @generated
 */
public interface BmodPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "bmod";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/bmod/Bmod";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "bmod";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  BmodPackage eINSTANCE = org.xtext.bmod.bmod.impl.BmodPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.bmod.bmod.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.bmod.bmod.impl.ModelImpl
   * @see org.xtext.bmod.bmod.impl.BmodPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.bmod.bmod.impl.FloorplanImpl <em>Floorplan</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.bmod.bmod.impl.FloorplanImpl
   * @see org.xtext.bmod.bmod.impl.BmodPackageImpl#getFloorplan()
   * @generated
   */
  int FLOORPLAN = 1;

  /**
   * The feature id for the '<em><b>Rooms</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FLOORPLAN__ROOMS = MODEL_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Doors</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FLOORPLAN__DOORS = MODEL_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Persons</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FLOORPLAN__PERSONS = MODEL_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Profiles</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FLOORPLAN__PROFILES = MODEL_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Levels</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FLOORPLAN__LEVELS = MODEL_FEATURE_COUNT + 4;

  /**
   * The number of structural features of the '<em>Floorplan</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FLOORPLAN_FEATURE_COUNT = MODEL_FEATURE_COUNT + 5;

  /**
   * The meta object id for the '{@link org.xtext.bmod.bmod.impl.RoomImpl <em>Room</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.bmod.bmod.impl.RoomImpl
   * @see org.xtext.bmod.bmod.impl.BmodPackageImpl#getRoom()
   * @generated
   */
  int ROOM = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOM__NAME = 0;

  /**
   * The feature id for the '<em><b>Named</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOM__NAMED = 1;

  /**
   * The feature id for the '<em><b>Area</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOM__AREA = 2;

  /**
   * The number of structural features of the '<em>Room</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOM_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.bmod.bmod.impl.DoorImpl <em>Door</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.bmod.bmod.impl.DoorImpl
   * @see org.xtext.bmod.bmod.impl.BmodPackageImpl#getDoor()
   * @generated
   */
  int DOOR = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOOR__NAME = 0;

  /**
   * The feature id for the '<em><b>From</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOOR__FROM = 1;

  /**
   * The feature id for the '<em><b>To</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOOR__TO = 2;

  /**
   * The number of structural features of the '<em>Door</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOOR_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.bmod.bmod.impl.ProfileImpl <em>Profile</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.bmod.bmod.impl.ProfileImpl
   * @see org.xtext.bmod.bmod.impl.BmodPackageImpl#getProfile()
   * @generated
   */
  int PROFILE = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROFILE__NAME = 0;

  /**
   * The number of structural features of the '<em>Profile</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROFILE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.bmod.bmod.impl.LevelImpl <em>Level</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.bmod.bmod.impl.LevelImpl
   * @see org.xtext.bmod.bmod.impl.BmodPackageImpl#getLevel()
   * @generated
   */
  int LEVEL = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LEVEL__NAME = 0;

  /**
   * The number of structural features of the '<em>Level</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LEVEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.bmod.bmod.impl.PersonImpl <em>Person</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.bmod.bmod.impl.PersonImpl
   * @see org.xtext.bmod.bmod.impl.BmodPackageImpl#getPerson()
   * @generated
   */
  int PERSON = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSON__NAME = 0;

  /**
   * The feature id for the '<em><b>Named</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSON__NAMED = 1;

  /**
   * The feature id for the '<em><b>Location</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSON__LOCATION = 2;

  /**
   * The feature id for the '<em><b>Profile</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSON__PROFILE = 3;

  /**
   * The feature id for the '<em><b>Level</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSON__LEVEL = 4;

  /**
   * The number of structural features of the '<em>Person</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSON_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link org.xtext.bmod.bmod.impl.CoordinateImpl <em>Coordinate</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.bmod.bmod.impl.CoordinateImpl
   * @see org.xtext.bmod.bmod.impl.BmodPackageImpl#getCoordinate()
   * @generated
   */
  int COORDINATE = 7;

  /**
   * The feature id for the '<em><b>X</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COORDINATE__X = 0;

  /**
   * The feature id for the '<em><b>Y</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COORDINATE__Y = 1;

  /**
   * The number of structural features of the '<em>Coordinate</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COORDINATE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.bmod.bmod.impl.AreaImpl <em>Area</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.bmod.bmod.impl.AreaImpl
   * @see org.xtext.bmod.bmod.impl.BmodPackageImpl#getArea()
   * @generated
   */
  int AREA = 8;

  /**
   * The feature id for the '<em><b>From</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AREA__FROM = 0;

  /**
   * The feature id for the '<em><b>To</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AREA__TO = 1;

  /**
   * The feature id for the '<em><b>Without</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AREA__WITHOUT = 2;

  /**
   * The number of structural features of the '<em>Area</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AREA_FEATURE_COUNT = 3;


  /**
   * Returns the meta object for class '{@link org.xtext.bmod.bmod.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.bmod.bmod.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for class '{@link org.xtext.bmod.bmod.Floorplan <em>Floorplan</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Floorplan</em>'.
   * @see org.xtext.bmod.bmod.Floorplan
   * @generated
   */
  EClass getFloorplan();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.bmod.bmod.Floorplan#getRooms <em>Rooms</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Rooms</em>'.
   * @see org.xtext.bmod.bmod.Floorplan#getRooms()
   * @see #getFloorplan()
   * @generated
   */
  EReference getFloorplan_Rooms();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.bmod.bmod.Floorplan#getDoors <em>Doors</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Doors</em>'.
   * @see org.xtext.bmod.bmod.Floorplan#getDoors()
   * @see #getFloorplan()
   * @generated
   */
  EReference getFloorplan_Doors();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.bmod.bmod.Floorplan#getPersons <em>Persons</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Persons</em>'.
   * @see org.xtext.bmod.bmod.Floorplan#getPersons()
   * @see #getFloorplan()
   * @generated
   */
  EReference getFloorplan_Persons();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.bmod.bmod.Floorplan#getProfiles <em>Profiles</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Profiles</em>'.
   * @see org.xtext.bmod.bmod.Floorplan#getProfiles()
   * @see #getFloorplan()
   * @generated
   */
  EReference getFloorplan_Profiles();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.bmod.bmod.Floorplan#getLevels <em>Levels</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Levels</em>'.
   * @see org.xtext.bmod.bmod.Floorplan#getLevels()
   * @see #getFloorplan()
   * @generated
   */
  EReference getFloorplan_Levels();

  /**
   * Returns the meta object for class '{@link org.xtext.bmod.bmod.Room <em>Room</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Room</em>'.
   * @see org.xtext.bmod.bmod.Room
   * @generated
   */
  EClass getRoom();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.bmod.bmod.Room#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.bmod.bmod.Room#getName()
   * @see #getRoom()
   * @generated
   */
  EAttribute getRoom_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.bmod.bmod.Room#getNamed <em>Named</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Named</em>'.
   * @see org.xtext.bmod.bmod.Room#getNamed()
   * @see #getRoom()
   * @generated
   */
  EAttribute getRoom_Named();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.bmod.bmod.Room#getArea <em>Area</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Area</em>'.
   * @see org.xtext.bmod.bmod.Room#getArea()
   * @see #getRoom()
   * @generated
   */
  EReference getRoom_Area();

  /**
   * Returns the meta object for class '{@link org.xtext.bmod.bmod.Door <em>Door</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Door</em>'.
   * @see org.xtext.bmod.bmod.Door
   * @generated
   */
  EClass getDoor();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.bmod.bmod.Door#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.bmod.bmod.Door#getName()
   * @see #getDoor()
   * @generated
   */
  EAttribute getDoor_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.bmod.bmod.Door#getFrom <em>From</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>From</em>'.
   * @see org.xtext.bmod.bmod.Door#getFrom()
   * @see #getDoor()
   * @generated
   */
  EReference getDoor_From();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.bmod.bmod.Door#getTo <em>To</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>To</em>'.
   * @see org.xtext.bmod.bmod.Door#getTo()
   * @see #getDoor()
   * @generated
   */
  EReference getDoor_To();

  /**
   * Returns the meta object for class '{@link org.xtext.bmod.bmod.Profile <em>Profile</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Profile</em>'.
   * @see org.xtext.bmod.bmod.Profile
   * @generated
   */
  EClass getProfile();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.bmod.bmod.Profile#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.bmod.bmod.Profile#getName()
   * @see #getProfile()
   * @generated
   */
  EAttribute getProfile_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.bmod.bmod.Level <em>Level</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Level</em>'.
   * @see org.xtext.bmod.bmod.Level
   * @generated
   */
  EClass getLevel();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.bmod.bmod.Level#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.bmod.bmod.Level#getName()
   * @see #getLevel()
   * @generated
   */
  EAttribute getLevel_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.bmod.bmod.Person <em>Person</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Person</em>'.
   * @see org.xtext.bmod.bmod.Person
   * @generated
   */
  EClass getPerson();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.bmod.bmod.Person#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.bmod.bmod.Person#getName()
   * @see #getPerson()
   * @generated
   */
  EAttribute getPerson_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.bmod.bmod.Person#getNamed <em>Named</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Named</em>'.
   * @see org.xtext.bmod.bmod.Person#getNamed()
   * @see #getPerson()
   * @generated
   */
  EAttribute getPerson_Named();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.bmod.bmod.Person#getLocation <em>Location</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Location</em>'.
   * @see org.xtext.bmod.bmod.Person#getLocation()
   * @see #getPerson()
   * @generated
   */
  EReference getPerson_Location();

  /**
   * Returns the meta object for the reference '{@link org.xtext.bmod.bmod.Person#getProfile <em>Profile</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Profile</em>'.
   * @see org.xtext.bmod.bmod.Person#getProfile()
   * @see #getPerson()
   * @generated
   */
  EReference getPerson_Profile();

  /**
   * Returns the meta object for the reference '{@link org.xtext.bmod.bmod.Person#getLevel <em>Level</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Level</em>'.
   * @see org.xtext.bmod.bmod.Person#getLevel()
   * @see #getPerson()
   * @generated
   */
  EReference getPerson_Level();

  /**
   * Returns the meta object for class '{@link org.xtext.bmod.bmod.Coordinate <em>Coordinate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Coordinate</em>'.
   * @see org.xtext.bmod.bmod.Coordinate
   * @generated
   */
  EClass getCoordinate();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.bmod.bmod.Coordinate#getX <em>X</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>X</em>'.
   * @see org.xtext.bmod.bmod.Coordinate#getX()
   * @see #getCoordinate()
   * @generated
   */
  EAttribute getCoordinate_X();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.bmod.bmod.Coordinate#getY <em>Y</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Y</em>'.
   * @see org.xtext.bmod.bmod.Coordinate#getY()
   * @see #getCoordinate()
   * @generated
   */
  EAttribute getCoordinate_Y();

  /**
   * Returns the meta object for class '{@link org.xtext.bmod.bmod.Area <em>Area</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Area</em>'.
   * @see org.xtext.bmod.bmod.Area
   * @generated
   */
  EClass getArea();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.bmod.bmod.Area#getFrom <em>From</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>From</em>'.
   * @see org.xtext.bmod.bmod.Area#getFrom()
   * @see #getArea()
   * @generated
   */
  EReference getArea_From();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.bmod.bmod.Area#getTo <em>To</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>To</em>'.
   * @see org.xtext.bmod.bmod.Area#getTo()
   * @see #getArea()
   * @generated
   */
  EReference getArea_To();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.bmod.bmod.Area#getWithout <em>Without</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Without</em>'.
   * @see org.xtext.bmod.bmod.Area#getWithout()
   * @see #getArea()
   * @generated
   */
  EReference getArea_Without();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  BmodFactory getBmodFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.bmod.bmod.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.bmod.bmod.impl.ModelImpl
     * @see org.xtext.bmod.bmod.impl.BmodPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '{@link org.xtext.bmod.bmod.impl.FloorplanImpl <em>Floorplan</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.bmod.bmod.impl.FloorplanImpl
     * @see org.xtext.bmod.bmod.impl.BmodPackageImpl#getFloorplan()
     * @generated
     */
    EClass FLOORPLAN = eINSTANCE.getFloorplan();

    /**
     * The meta object literal for the '<em><b>Rooms</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FLOORPLAN__ROOMS = eINSTANCE.getFloorplan_Rooms();

    /**
     * The meta object literal for the '<em><b>Doors</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FLOORPLAN__DOORS = eINSTANCE.getFloorplan_Doors();

    /**
     * The meta object literal for the '<em><b>Persons</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FLOORPLAN__PERSONS = eINSTANCE.getFloorplan_Persons();

    /**
     * The meta object literal for the '<em><b>Profiles</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FLOORPLAN__PROFILES = eINSTANCE.getFloorplan_Profiles();

    /**
     * The meta object literal for the '<em><b>Levels</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FLOORPLAN__LEVELS = eINSTANCE.getFloorplan_Levels();

    /**
     * The meta object literal for the '{@link org.xtext.bmod.bmod.impl.RoomImpl <em>Room</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.bmod.bmod.impl.RoomImpl
     * @see org.xtext.bmod.bmod.impl.BmodPackageImpl#getRoom()
     * @generated
     */
    EClass ROOM = eINSTANCE.getRoom();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROOM__NAME = eINSTANCE.getRoom_Name();

    /**
     * The meta object literal for the '<em><b>Named</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROOM__NAMED = eINSTANCE.getRoom_Named();

    /**
     * The meta object literal for the '<em><b>Area</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROOM__AREA = eINSTANCE.getRoom_Area();

    /**
     * The meta object literal for the '{@link org.xtext.bmod.bmod.impl.DoorImpl <em>Door</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.bmod.bmod.impl.DoorImpl
     * @see org.xtext.bmod.bmod.impl.BmodPackageImpl#getDoor()
     * @generated
     */
    EClass DOOR = eINSTANCE.getDoor();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DOOR__NAME = eINSTANCE.getDoor_Name();

    /**
     * The meta object literal for the '<em><b>From</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DOOR__FROM = eINSTANCE.getDoor_From();

    /**
     * The meta object literal for the '<em><b>To</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DOOR__TO = eINSTANCE.getDoor_To();

    /**
     * The meta object literal for the '{@link org.xtext.bmod.bmod.impl.ProfileImpl <em>Profile</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.bmod.bmod.impl.ProfileImpl
     * @see org.xtext.bmod.bmod.impl.BmodPackageImpl#getProfile()
     * @generated
     */
    EClass PROFILE = eINSTANCE.getProfile();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROFILE__NAME = eINSTANCE.getProfile_Name();

    /**
     * The meta object literal for the '{@link org.xtext.bmod.bmod.impl.LevelImpl <em>Level</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.bmod.bmod.impl.LevelImpl
     * @see org.xtext.bmod.bmod.impl.BmodPackageImpl#getLevel()
     * @generated
     */
    EClass LEVEL = eINSTANCE.getLevel();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LEVEL__NAME = eINSTANCE.getLevel_Name();

    /**
     * The meta object literal for the '{@link org.xtext.bmod.bmod.impl.PersonImpl <em>Person</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.bmod.bmod.impl.PersonImpl
     * @see org.xtext.bmod.bmod.impl.BmodPackageImpl#getPerson()
     * @generated
     */
    EClass PERSON = eINSTANCE.getPerson();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PERSON__NAME = eINSTANCE.getPerson_Name();

    /**
     * The meta object literal for the '<em><b>Named</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PERSON__NAMED = eINSTANCE.getPerson_Named();

    /**
     * The meta object literal for the '<em><b>Location</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PERSON__LOCATION = eINSTANCE.getPerson_Location();

    /**
     * The meta object literal for the '<em><b>Profile</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PERSON__PROFILE = eINSTANCE.getPerson_Profile();

    /**
     * The meta object literal for the '<em><b>Level</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PERSON__LEVEL = eINSTANCE.getPerson_Level();

    /**
     * The meta object literal for the '{@link org.xtext.bmod.bmod.impl.CoordinateImpl <em>Coordinate</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.bmod.bmod.impl.CoordinateImpl
     * @see org.xtext.bmod.bmod.impl.BmodPackageImpl#getCoordinate()
     * @generated
     */
    EClass COORDINATE = eINSTANCE.getCoordinate();

    /**
     * The meta object literal for the '<em><b>X</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COORDINATE__X = eINSTANCE.getCoordinate_X();

    /**
     * The meta object literal for the '<em><b>Y</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COORDINATE__Y = eINSTANCE.getCoordinate_Y();

    /**
     * The meta object literal for the '{@link org.xtext.bmod.bmod.impl.AreaImpl <em>Area</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.bmod.bmod.impl.AreaImpl
     * @see org.xtext.bmod.bmod.impl.BmodPackageImpl#getArea()
     * @generated
     */
    EClass AREA = eINSTANCE.getArea();

    /**
     * The meta object literal for the '<em><b>From</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AREA__FROM = eINSTANCE.getArea_From();

    /**
     * The meta object literal for the '<em><b>To</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AREA__TO = eINSTANCE.getArea_To();

    /**
     * The meta object literal for the '<em><b>Without</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AREA__WITHOUT = eINSTANCE.getArea_Without();

  }

} //BmodPackage
