/**
 * generated by Xtext 2.16.0
 */
package org.xtext.bmod.bmod;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.bmod.bmod.BmodFactory
 * @model kind="package"
 * @generated
 */
public interface BmodPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "bmod";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/bmod/Bmod";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "bmod";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  BmodPackage eINSTANCE = org.xtext.bmod.bmod.impl.BmodPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.bmod.bmod.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.bmod.bmod.impl.ModelImpl
   * @see org.xtext.bmod.bmod.impl.BmodPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.bmod.bmod.impl.FloorplanImpl <em>Floorplan</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.bmod.bmod.impl.FloorplanImpl
   * @see org.xtext.bmod.bmod.impl.BmodPackageImpl#getFloorplan()
   * @generated
   */
  int FLOORPLAN = 1;

  /**
   * The feature id for the '<em><b>Imports</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FLOORPLAN__IMPORTS = MODEL_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Rooms</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FLOORPLAN__ROOMS = MODEL_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Doors</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FLOORPLAN__DOORS = MODEL_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Persons</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FLOORPLAN__PERSONS = MODEL_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Exits</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FLOORPLAN__EXITS = MODEL_FEATURE_COUNT + 4;

  /**
   * The feature id for the '<em><b>Fires</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FLOORPLAN__FIRES = MODEL_FEATURE_COUNT + 5;

  /**
   * The feature id for the '<em><b>Signs</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FLOORPLAN__SIGNS = MODEL_FEATURE_COUNT + 6;

  /**
   * The number of structural features of the '<em>Floorplan</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FLOORPLAN_FEATURE_COUNT = MODEL_FEATURE_COUNT + 7;

  /**
   * The meta object id for the '{@link org.xtext.bmod.bmod.impl.ImportImpl <em>Import</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.bmod.bmod.impl.ImportImpl
   * @see org.xtext.bmod.bmod.impl.BmodPackageImpl#getImport()
   * @generated
   */
  int IMPORT = 2;

  /**
   * The feature id for the '<em><b>Import URI</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPORT__IMPORT_URI = 0;

  /**
   * The number of structural features of the '<em>Import</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPORT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.bmod.bmod.impl.RoomImpl <em>Room</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.bmod.bmod.impl.RoomImpl
   * @see org.xtext.bmod.bmod.impl.BmodPackageImpl#getRoom()
   * @generated
   */
  int ROOM = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOM__NAME = 0;

  /**
   * The feature id for the '<em><b>Has Capacity</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOM__HAS_CAPACITY = 1;

  /**
   * The feature id for the '<em><b>Capacity</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOM__CAPACITY = 2;

  /**
   * The feature id for the '<em><b>Areas</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOM__AREAS = 3;

  /**
   * The number of structural features of the '<em>Room</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOM_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.bmod.bmod.impl.DoorImpl <em>Door</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.bmod.bmod.impl.DoorImpl
   * @see org.xtext.bmod.bmod.impl.BmodPackageImpl#getDoor()
   * @generated
   */
  int DOOR = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOOR__NAME = 0;

  /**
   * The feature id for the '<em><b>From</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOOR__FROM = 1;

  /**
   * The feature id for the '<em><b>To</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOOR__TO = 2;

  /**
   * The number of structural features of the '<em>Door</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOOR_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.bmod.bmod.impl.PersonImpl <em>Person</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.bmod.bmod.impl.PersonImpl
   * @see org.xtext.bmod.bmod.impl.BmodPackageImpl#getPerson()
   * @generated
   */
  int PERSON = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSON__NAME = 0;

  /**
   * The feature id for the '<em><b>Location</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSON__LOCATION = 1;

  /**
   * The feature id for the '<em><b>Action</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSON__ACTION = 2;

  /**
   * The number of structural features of the '<em>Person</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSON_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.bmod.bmod.impl.ExitImpl <em>Exit</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.bmod.bmod.impl.ExitImpl
   * @see org.xtext.bmod.bmod.impl.BmodPackageImpl#getExit()
   * @generated
   */
  int EXIT = 6;

  /**
   * The feature id for the '<em><b>Location</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXIT__LOCATION = 0;

  /**
   * The number of structural features of the '<em>Exit</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXIT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.bmod.bmod.impl.FireImpl <em>Fire</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.bmod.bmod.impl.FireImpl
   * @see org.xtext.bmod.bmod.impl.BmodPackageImpl#getFire()
   * @generated
   */
  int FIRE = 7;

  /**
   * The feature id for the '<em><b>Location</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIRE__LOCATION = 0;

  /**
   * The number of structural features of the '<em>Fire</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIRE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.bmod.bmod.impl.EmergencySignImpl <em>Emergency Sign</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.bmod.bmod.impl.EmergencySignImpl
   * @see org.xtext.bmod.bmod.impl.BmodPackageImpl#getEmergencySign()
   * @generated
   */
  int EMERGENCY_SIGN = 8;

  /**
   * The feature id for the '<em><b>From</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EMERGENCY_SIGN__FROM = 0;

  /**
   * The feature id for the '<em><b>Ref</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EMERGENCY_SIGN__REF = 1;

  /**
   * The number of structural features of the '<em>Emergency Sign</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EMERGENCY_SIGN_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.bmod.bmod.impl.DoorRefImpl <em>Door Ref</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.bmod.bmod.impl.DoorRefImpl
   * @see org.xtext.bmod.bmod.impl.BmodPackageImpl#getDoorRef()
   * @generated
   */
  int DOOR_REF = 9;

  /**
   * The feature id for the '<em><b>To</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOOR_REF__TO = 0;

  /**
   * The number of structural features of the '<em>Door Ref</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOOR_REF_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.bmod.bmod.impl.CoordinateImpl <em>Coordinate</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.bmod.bmod.impl.CoordinateImpl
   * @see org.xtext.bmod.bmod.impl.BmodPackageImpl#getCoordinate()
   * @generated
   */
  int COORDINATE = 10;

  /**
   * The feature id for the '<em><b>X</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COORDINATE__X = 0;

  /**
   * The feature id for the '<em><b>Y</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COORDINATE__Y = 1;

  /**
   * The number of structural features of the '<em>Coordinate</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COORDINATE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.bmod.bmod.impl.AreaImpl <em>Area</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.bmod.bmod.impl.AreaImpl
   * @see org.xtext.bmod.bmod.impl.BmodPackageImpl#getArea()
   * @generated
   */
  int AREA = 11;

  /**
   * The feature id for the '<em><b>From</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AREA__FROM = 0;

  /**
   * The feature id for the '<em><b>To</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AREA__TO = 1;

  /**
   * The feature id for the '<em><b>Without</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AREA__WITHOUT = 2;

  /**
   * The number of structural features of the '<em>Area</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AREA_FEATURE_COUNT = 3;


  /**
   * Returns the meta object for class '{@link org.xtext.bmod.bmod.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.bmod.bmod.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for class '{@link org.xtext.bmod.bmod.Floorplan <em>Floorplan</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Floorplan</em>'.
   * @see org.xtext.bmod.bmod.Floorplan
   * @generated
   */
  EClass getFloorplan();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.bmod.bmod.Floorplan#getImports <em>Imports</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Imports</em>'.
   * @see org.xtext.bmod.bmod.Floorplan#getImports()
   * @see #getFloorplan()
   * @generated
   */
  EReference getFloorplan_Imports();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.bmod.bmod.Floorplan#getRooms <em>Rooms</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Rooms</em>'.
   * @see org.xtext.bmod.bmod.Floorplan#getRooms()
   * @see #getFloorplan()
   * @generated
   */
  EReference getFloorplan_Rooms();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.bmod.bmod.Floorplan#getDoors <em>Doors</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Doors</em>'.
   * @see org.xtext.bmod.bmod.Floorplan#getDoors()
   * @see #getFloorplan()
   * @generated
   */
  EReference getFloorplan_Doors();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.bmod.bmod.Floorplan#getPersons <em>Persons</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Persons</em>'.
   * @see org.xtext.bmod.bmod.Floorplan#getPersons()
   * @see #getFloorplan()
   * @generated
   */
  EReference getFloorplan_Persons();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.bmod.bmod.Floorplan#getExits <em>Exits</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Exits</em>'.
   * @see org.xtext.bmod.bmod.Floorplan#getExits()
   * @see #getFloorplan()
   * @generated
   */
  EReference getFloorplan_Exits();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.bmod.bmod.Floorplan#getFires <em>Fires</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Fires</em>'.
   * @see org.xtext.bmod.bmod.Floorplan#getFires()
   * @see #getFloorplan()
   * @generated
   */
  EReference getFloorplan_Fires();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.bmod.bmod.Floorplan#getSigns <em>Signs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Signs</em>'.
   * @see org.xtext.bmod.bmod.Floorplan#getSigns()
   * @see #getFloorplan()
   * @generated
   */
  EReference getFloorplan_Signs();

  /**
   * Returns the meta object for class '{@link org.xtext.bmod.bmod.Import <em>Import</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Import</em>'.
   * @see org.xtext.bmod.bmod.Import
   * @generated
   */
  EClass getImport();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.bmod.bmod.Import#getImportURI <em>Import URI</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Import URI</em>'.
   * @see org.xtext.bmod.bmod.Import#getImportURI()
   * @see #getImport()
   * @generated
   */
  EAttribute getImport_ImportURI();

  /**
   * Returns the meta object for class '{@link org.xtext.bmod.bmod.Room <em>Room</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Room</em>'.
   * @see org.xtext.bmod.bmod.Room
   * @generated
   */
  EClass getRoom();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.bmod.bmod.Room#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.bmod.bmod.Room#getName()
   * @see #getRoom()
   * @generated
   */
  EAttribute getRoom_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.bmod.bmod.Room#isHasCapacity <em>Has Capacity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Has Capacity</em>'.
   * @see org.xtext.bmod.bmod.Room#isHasCapacity()
   * @see #getRoom()
   * @generated
   */
  EAttribute getRoom_HasCapacity();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.bmod.bmod.Room#getCapacity <em>Capacity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Capacity</em>'.
   * @see org.xtext.bmod.bmod.Room#getCapacity()
   * @see #getRoom()
   * @generated
   */
  EAttribute getRoom_Capacity();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.bmod.bmod.Room#getAreas <em>Areas</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Areas</em>'.
   * @see org.xtext.bmod.bmod.Room#getAreas()
   * @see #getRoom()
   * @generated
   */
  EReference getRoom_Areas();

  /**
   * Returns the meta object for class '{@link org.xtext.bmod.bmod.Door <em>Door</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Door</em>'.
   * @see org.xtext.bmod.bmod.Door
   * @generated
   */
  EClass getDoor();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.bmod.bmod.Door#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.bmod.bmod.Door#getName()
   * @see #getDoor()
   * @generated
   */
  EAttribute getDoor_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.bmod.bmod.Door#getFrom <em>From</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>From</em>'.
   * @see org.xtext.bmod.bmod.Door#getFrom()
   * @see #getDoor()
   * @generated
   */
  EReference getDoor_From();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.bmod.bmod.Door#getTo <em>To</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>To</em>'.
   * @see org.xtext.bmod.bmod.Door#getTo()
   * @see #getDoor()
   * @generated
   */
  EReference getDoor_To();

  /**
   * Returns the meta object for class '{@link org.xtext.bmod.bmod.Person <em>Person</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Person</em>'.
   * @see org.xtext.bmod.bmod.Person
   * @generated
   */
  EClass getPerson();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.bmod.bmod.Person#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.bmod.bmod.Person#getName()
   * @see #getPerson()
   * @generated
   */
  EAttribute getPerson_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.bmod.bmod.Person#getLocation <em>Location</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Location</em>'.
   * @see org.xtext.bmod.bmod.Person#getLocation()
   * @see #getPerson()
   * @generated
   */
  EReference getPerson_Location();

  /**
   * Returns the meta object for the reference '{@link org.xtext.bmod.bmod.Person#getAction <em>Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Action</em>'.
   * @see org.xtext.bmod.bmod.Person#getAction()
   * @see #getPerson()
   * @generated
   */
  EReference getPerson_Action();

  /**
   * Returns the meta object for class '{@link org.xtext.bmod.bmod.Exit <em>Exit</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Exit</em>'.
   * @see org.xtext.bmod.bmod.Exit
   * @generated
   */
  EClass getExit();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.bmod.bmod.Exit#getLocation <em>Location</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Location</em>'.
   * @see org.xtext.bmod.bmod.Exit#getLocation()
   * @see #getExit()
   * @generated
   */
  EReference getExit_Location();

  /**
   * Returns the meta object for class '{@link org.xtext.bmod.bmod.Fire <em>Fire</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Fire</em>'.
   * @see org.xtext.bmod.bmod.Fire
   * @generated
   */
  EClass getFire();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.bmod.bmod.Fire#getLocation <em>Location</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Location</em>'.
   * @see org.xtext.bmod.bmod.Fire#getLocation()
   * @see #getFire()
   * @generated
   */
  EReference getFire_Location();

  /**
   * Returns the meta object for class '{@link org.xtext.bmod.bmod.EmergencySign <em>Emergency Sign</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Emergency Sign</em>'.
   * @see org.xtext.bmod.bmod.EmergencySign
   * @generated
   */
  EClass getEmergencySign();

  /**
   * Returns the meta object for the reference '{@link org.xtext.bmod.bmod.EmergencySign#getFrom <em>From</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>From</em>'.
   * @see org.xtext.bmod.bmod.EmergencySign#getFrom()
   * @see #getEmergencySign()
   * @generated
   */
  EReference getEmergencySign_From();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.bmod.bmod.EmergencySign#getRef <em>Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Ref</em>'.
   * @see org.xtext.bmod.bmod.EmergencySign#getRef()
   * @see #getEmergencySign()
   * @generated
   */
  EReference getEmergencySign_Ref();

  /**
   * Returns the meta object for class '{@link org.xtext.bmod.bmod.DoorRef <em>Door Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Door Ref</em>'.
   * @see org.xtext.bmod.bmod.DoorRef
   * @generated
   */
  EClass getDoorRef();

  /**
   * Returns the meta object for the reference '{@link org.xtext.bmod.bmod.DoorRef#getTo <em>To</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>To</em>'.
   * @see org.xtext.bmod.bmod.DoorRef#getTo()
   * @see #getDoorRef()
   * @generated
   */
  EReference getDoorRef_To();

  /**
   * Returns the meta object for class '{@link org.xtext.bmod.bmod.Coordinate <em>Coordinate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Coordinate</em>'.
   * @see org.xtext.bmod.bmod.Coordinate
   * @generated
   */
  EClass getCoordinate();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.bmod.bmod.Coordinate#getX <em>X</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>X</em>'.
   * @see org.xtext.bmod.bmod.Coordinate#getX()
   * @see #getCoordinate()
   * @generated
   */
  EAttribute getCoordinate_X();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.bmod.bmod.Coordinate#getY <em>Y</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Y</em>'.
   * @see org.xtext.bmod.bmod.Coordinate#getY()
   * @see #getCoordinate()
   * @generated
   */
  EAttribute getCoordinate_Y();

  /**
   * Returns the meta object for class '{@link org.xtext.bmod.bmod.Area <em>Area</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Area</em>'.
   * @see org.xtext.bmod.bmod.Area
   * @generated
   */
  EClass getArea();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.bmod.bmod.Area#getFrom <em>From</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>From</em>'.
   * @see org.xtext.bmod.bmod.Area#getFrom()
   * @see #getArea()
   * @generated
   */
  EReference getArea_From();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.bmod.bmod.Area#getTo <em>To</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>To</em>'.
   * @see org.xtext.bmod.bmod.Area#getTo()
   * @see #getArea()
   * @generated
   */
  EReference getArea_To();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.bmod.bmod.Area#getWithout <em>Without</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Without</em>'.
   * @see org.xtext.bmod.bmod.Area#getWithout()
   * @see #getArea()
   * @generated
   */
  EReference getArea_Without();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  BmodFactory getBmodFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.bmod.bmod.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.bmod.bmod.impl.ModelImpl
     * @see org.xtext.bmod.bmod.impl.BmodPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '{@link org.xtext.bmod.bmod.impl.FloorplanImpl <em>Floorplan</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.bmod.bmod.impl.FloorplanImpl
     * @see org.xtext.bmod.bmod.impl.BmodPackageImpl#getFloorplan()
     * @generated
     */
    EClass FLOORPLAN = eINSTANCE.getFloorplan();

    /**
     * The meta object literal for the '<em><b>Imports</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FLOORPLAN__IMPORTS = eINSTANCE.getFloorplan_Imports();

    /**
     * The meta object literal for the '<em><b>Rooms</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FLOORPLAN__ROOMS = eINSTANCE.getFloorplan_Rooms();

    /**
     * The meta object literal for the '<em><b>Doors</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FLOORPLAN__DOORS = eINSTANCE.getFloorplan_Doors();

    /**
     * The meta object literal for the '<em><b>Persons</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FLOORPLAN__PERSONS = eINSTANCE.getFloorplan_Persons();

    /**
     * The meta object literal for the '<em><b>Exits</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FLOORPLAN__EXITS = eINSTANCE.getFloorplan_Exits();

    /**
     * The meta object literal for the '<em><b>Fires</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FLOORPLAN__FIRES = eINSTANCE.getFloorplan_Fires();

    /**
     * The meta object literal for the '<em><b>Signs</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FLOORPLAN__SIGNS = eINSTANCE.getFloorplan_Signs();

    /**
     * The meta object literal for the '{@link org.xtext.bmod.bmod.impl.ImportImpl <em>Import</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.bmod.bmod.impl.ImportImpl
     * @see org.xtext.bmod.bmod.impl.BmodPackageImpl#getImport()
     * @generated
     */
    EClass IMPORT = eINSTANCE.getImport();

    /**
     * The meta object literal for the '<em><b>Import URI</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IMPORT__IMPORT_URI = eINSTANCE.getImport_ImportURI();

    /**
     * The meta object literal for the '{@link org.xtext.bmod.bmod.impl.RoomImpl <em>Room</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.bmod.bmod.impl.RoomImpl
     * @see org.xtext.bmod.bmod.impl.BmodPackageImpl#getRoom()
     * @generated
     */
    EClass ROOM = eINSTANCE.getRoom();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROOM__NAME = eINSTANCE.getRoom_Name();

    /**
     * The meta object literal for the '<em><b>Has Capacity</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROOM__HAS_CAPACITY = eINSTANCE.getRoom_HasCapacity();

    /**
     * The meta object literal for the '<em><b>Capacity</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROOM__CAPACITY = eINSTANCE.getRoom_Capacity();

    /**
     * The meta object literal for the '<em><b>Areas</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROOM__AREAS = eINSTANCE.getRoom_Areas();

    /**
     * The meta object literal for the '{@link org.xtext.bmod.bmod.impl.DoorImpl <em>Door</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.bmod.bmod.impl.DoorImpl
     * @see org.xtext.bmod.bmod.impl.BmodPackageImpl#getDoor()
     * @generated
     */
    EClass DOOR = eINSTANCE.getDoor();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DOOR__NAME = eINSTANCE.getDoor_Name();

    /**
     * The meta object literal for the '<em><b>From</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DOOR__FROM = eINSTANCE.getDoor_From();

    /**
     * The meta object literal for the '<em><b>To</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DOOR__TO = eINSTANCE.getDoor_To();

    /**
     * The meta object literal for the '{@link org.xtext.bmod.bmod.impl.PersonImpl <em>Person</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.bmod.bmod.impl.PersonImpl
     * @see org.xtext.bmod.bmod.impl.BmodPackageImpl#getPerson()
     * @generated
     */
    EClass PERSON = eINSTANCE.getPerson();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PERSON__NAME = eINSTANCE.getPerson_Name();

    /**
     * The meta object literal for the '<em><b>Location</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PERSON__LOCATION = eINSTANCE.getPerson_Location();

    /**
     * The meta object literal for the '<em><b>Action</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PERSON__ACTION = eINSTANCE.getPerson_Action();

    /**
     * The meta object literal for the '{@link org.xtext.bmod.bmod.impl.ExitImpl <em>Exit</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.bmod.bmod.impl.ExitImpl
     * @see org.xtext.bmod.bmod.impl.BmodPackageImpl#getExit()
     * @generated
     */
    EClass EXIT = eINSTANCE.getExit();

    /**
     * The meta object literal for the '<em><b>Location</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXIT__LOCATION = eINSTANCE.getExit_Location();

    /**
     * The meta object literal for the '{@link org.xtext.bmod.bmod.impl.FireImpl <em>Fire</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.bmod.bmod.impl.FireImpl
     * @see org.xtext.bmod.bmod.impl.BmodPackageImpl#getFire()
     * @generated
     */
    EClass FIRE = eINSTANCE.getFire();

    /**
     * The meta object literal for the '<em><b>Location</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FIRE__LOCATION = eINSTANCE.getFire_Location();

    /**
     * The meta object literal for the '{@link org.xtext.bmod.bmod.impl.EmergencySignImpl <em>Emergency Sign</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.bmod.bmod.impl.EmergencySignImpl
     * @see org.xtext.bmod.bmod.impl.BmodPackageImpl#getEmergencySign()
     * @generated
     */
    EClass EMERGENCY_SIGN = eINSTANCE.getEmergencySign();

    /**
     * The meta object literal for the '<em><b>From</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EMERGENCY_SIGN__FROM = eINSTANCE.getEmergencySign_From();

    /**
     * The meta object literal for the '<em><b>Ref</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EMERGENCY_SIGN__REF = eINSTANCE.getEmergencySign_Ref();

    /**
     * The meta object literal for the '{@link org.xtext.bmod.bmod.impl.DoorRefImpl <em>Door Ref</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.bmod.bmod.impl.DoorRefImpl
     * @see org.xtext.bmod.bmod.impl.BmodPackageImpl#getDoorRef()
     * @generated
     */
    EClass DOOR_REF = eINSTANCE.getDoorRef();

    /**
     * The meta object literal for the '<em><b>To</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DOOR_REF__TO = eINSTANCE.getDoorRef_To();

    /**
     * The meta object literal for the '{@link org.xtext.bmod.bmod.impl.CoordinateImpl <em>Coordinate</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.bmod.bmod.impl.CoordinateImpl
     * @see org.xtext.bmod.bmod.impl.BmodPackageImpl#getCoordinate()
     * @generated
     */
    EClass COORDINATE = eINSTANCE.getCoordinate();

    /**
     * The meta object literal for the '<em><b>X</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COORDINATE__X = eINSTANCE.getCoordinate_X();

    /**
     * The meta object literal for the '<em><b>Y</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COORDINATE__Y = eINSTANCE.getCoordinate_Y();

    /**
     * The meta object literal for the '{@link org.xtext.bmod.bmod.impl.AreaImpl <em>Area</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.bmod.bmod.impl.AreaImpl
     * @see org.xtext.bmod.bmod.impl.BmodPackageImpl#getArea()
     * @generated
     */
    EClass AREA = eINSTANCE.getArea();

    /**
     * The meta object literal for the '<em><b>From</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AREA__FROM = eINSTANCE.getArea_From();

    /**
     * The meta object literal for the '<em><b>To</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AREA__TO = eINSTANCE.getArea_To();

    /**
     * The meta object literal for the '<em><b>Without</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AREA__WITHOUT = eINSTANCE.getArea_Without();

  }

} //BmodPackage
