/**
 * generated by Xtext 2.16.0
 */
package org.xtext.bmod.bmod;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Emergency Sign</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.bmod.bmod.EmergencySign#getFrom <em>From</em>}</li>
 *   <li>{@link org.xtext.bmod.bmod.EmergencySign#getRef <em>Ref</em>}</li>
 * </ul>
 *
 * @see org.xtext.bmod.bmod.BmodPackage#getEmergencySign()
 * @model
 * @generated
 */
public interface EmergencySign extends EObject
{
  /**
   * Returns the value of the '<em><b>From</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>From</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>From</em>' reference.
   * @see #setFrom(Door)
   * @see org.xtext.bmod.bmod.BmodPackage#getEmergencySign_From()
   * @model
   * @generated
   */
  Door getFrom();

  /**
   * Sets the value of the '{@link org.xtext.bmod.bmod.EmergencySign#getFrom <em>From</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>From</em>' reference.
   * @see #getFrom()
   * @generated
   */
  void setFrom(Door value);

  /**
   * Returns the value of the '<em><b>Ref</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ref</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ref</em>' containment reference.
   * @see #setRef(DoorRef)
   * @see org.xtext.bmod.bmod.BmodPackage#getEmergencySign_Ref()
   * @model containment="true"
   * @generated
   */
  DoorRef getRef();

  /**
   * Sets the value of the '{@link org.xtext.bmod.bmod.EmergencySign#getRef <em>Ref</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ref</em>' containment reference.
   * @see #getRef()
   * @generated
   */
  void setRef(DoorRef value);

} // EmergencySign
