/**
 * generated by Xtext 2.16.0
 */
package org.xtext.bmod.bmod;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Floorplan</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.bmod.bmod.Floorplan#getRooms <em>Rooms</em>}</li>
 *   <li>{@link org.xtext.bmod.bmod.Floorplan#getDoors <em>Doors</em>}</li>
 *   <li>{@link org.xtext.bmod.bmod.Floorplan#getPersons <em>Persons</em>}</li>
 *   <li>{@link org.xtext.bmod.bmod.Floorplan#getExits <em>Exits</em>}</li>
 *   <li>{@link org.xtext.bmod.bmod.Floorplan#getSigns <em>Signs</em>}</li>
 *   <li>{@link org.xtext.bmod.bmod.Floorplan#getDancons <em>Dancons</em>}</li>
 * </ul>
 *
 * @see org.xtext.bmod.bmod.BmodPackage#getFloorplan()
 * @model
 * @generated
 */
public interface Floorplan extends Model
{
  /**
   * Returns the value of the '<em><b>Rooms</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.bmod.bmod.Room}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Rooms</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rooms</em>' containment reference list.
   * @see org.xtext.bmod.bmod.BmodPackage#getFloorplan_Rooms()
   * @model containment="true"
   * @generated
   */
  EList<Room> getRooms();

  /**
   * Returns the value of the '<em><b>Doors</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.bmod.bmod.Door}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Doors</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Doors</em>' containment reference list.
   * @see org.xtext.bmod.bmod.BmodPackage#getFloorplan_Doors()
   * @model containment="true"
   * @generated
   */
  EList<Door> getDoors();

  /**
   * Returns the value of the '<em><b>Persons</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.bmod.bmod.Person}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Persons</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Persons</em>' containment reference list.
   * @see org.xtext.bmod.bmod.BmodPackage#getFloorplan_Persons()
   * @model containment="true"
   * @generated
   */
  EList<Person> getPersons();

  /**
   * Returns the value of the '<em><b>Exits</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.bmod.bmod.Exit}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Exits</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exits</em>' containment reference list.
   * @see org.xtext.bmod.bmod.BmodPackage#getFloorplan_Exits()
   * @model containment="true"
   * @generated
   */
  EList<Exit> getExits();

  /**
   * Returns the value of the '<em><b>Signs</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.bmod.bmod.EmergencySign}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Signs</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Signs</em>' containment reference list.
   * @see org.xtext.bmod.bmod.BmodPackage#getFloorplan_Signs()
   * @model containment="true"
   * @generated
   */
  EList<EmergencySign> getSigns();

  /**
   * Returns the value of the '<em><b>Dancons</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.bmod.bmod.DangerousCondition}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Dancons</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dancons</em>' containment reference list.
   * @see org.xtext.bmod.bmod.BmodPackage#getFloorplan_Dancons()
   * @model containment="true"
   * @generated
   */
  EList<DangerousCondition> getDancons();

} // Floorplan
