/**
 * generated by Xtext 2.16.0
 */
package org.xtext.bmod.bmod;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Perception</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.bmod.bmod.Perception#getExisting <em>Existing</em>}</li>
 *   <li>{@link org.xtext.bmod.bmod.Perception#getCustom <em>Custom</em>}</li>
 * </ul>
 *
 * @see org.xtext.bmod.bmod.BmodPackage#getPerception()
 * @model
 * @generated
 */
public interface Perception extends EObject
{
  /**
   * Returns the value of the '<em><b>Existing</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.bmod.bmod.PerceptionEnum}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Existing</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Existing</em>' attribute.
   * @see org.xtext.bmod.bmod.PerceptionEnum
   * @see #setExisting(PerceptionEnum)
   * @see org.xtext.bmod.bmod.BmodPackage#getPerception_Existing()
   * @model
   * @generated
   */
  PerceptionEnum getExisting();

  /**
   * Sets the value of the '{@link org.xtext.bmod.bmod.Perception#getExisting <em>Existing</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Existing</em>' attribute.
   * @see org.xtext.bmod.bmod.PerceptionEnum
   * @see #getExisting()
   * @generated
   */
  void setExisting(PerceptionEnum value);

  /**
   * Returns the value of the '<em><b>Custom</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Custom</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Custom</em>' reference.
   * @see #setCustom(PerceptionLevel)
   * @see org.xtext.bmod.bmod.BmodPackage#getPerception_Custom()
   * @model
   * @generated
   */
  PerceptionLevel getCustom();

  /**
   * Sets the value of the '{@link org.xtext.bmod.bmod.Perception#getCustom <em>Custom</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Custom</em>' reference.
   * @see #getCustom()
   * @generated
   */
  void setCustom(PerceptionLevel value);

} // Perception
