/**
 * generated by Xtext 2.16.0
 */
package org.xtext.ha;

import org.xtext.ha.AbstractRulesRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class RulesRuntimeModule extends AbstractRulesRuntimeModule {
}
