/**
 * generated by Xtext 2.16.0
 */
package org.xtext.bmod.breact;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>Locatable</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see org.xtext.bmod.breact.BreactPackage#getLocatable()
 * @model
 * @generated
 */
public enum Locatable implements Enumerator
{
  /**
   * The '<em><b>Cell</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #CELL_VALUE
   * @generated
   * @ordered
   */
  CELL(0, "Cell", "Cell"),

  /**
   * The '<em><b>Door</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #DOOR_VALUE
   * @generated
   * @ordered
   */
  DOOR(1, "Door", "Door"),

  /**
   * The '<em><b>Exit</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #EXIT_VALUE
   * @generated
   * @ordered
   */
  EXIT(2, "Exit", "Exit"),

  /**
   * The '<em><b>Fire</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #FIRE_VALUE
   * @generated
   * @ordered
   */
  FIRE(3, "Fire", "Fire"),

  /**
   * The '<em><b>Person</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PERSON_VALUE
   * @generated
   * @ordered
   */
  PERSON(4, "Person", "Person");

  /**
   * The '<em><b>Cell</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Cell</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #CELL
   * @model name="Cell"
   * @generated
   * @ordered
   */
  public static final int CELL_VALUE = 0;

  /**
   * The '<em><b>Door</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Door</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #DOOR
   * @model name="Door"
   * @generated
   * @ordered
   */
  public static final int DOOR_VALUE = 1;

  /**
   * The '<em><b>Exit</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Exit</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #EXIT
   * @model name="Exit"
   * @generated
   * @ordered
   */
  public static final int EXIT_VALUE = 2;

  /**
   * The '<em><b>Fire</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Fire</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #FIRE
   * @model name="Fire"
   * @generated
   * @ordered
   */
  public static final int FIRE_VALUE = 3;

  /**
   * The '<em><b>Person</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Person</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #PERSON
   * @model name="Person"
   * @generated
   * @ordered
   */
  public static final int PERSON_VALUE = 4;

  /**
   * An array of all the '<em><b>Locatable</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final Locatable[] VALUES_ARRAY =
    new Locatable[]
    {
      CELL,
      DOOR,
      EXIT,
      FIRE,
      PERSON,
    };

  /**
   * A public read-only list of all the '<em><b>Locatable</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<Locatable> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>Locatable</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Locatable get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      Locatable result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Locatable</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Locatable getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      Locatable result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Locatable</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Locatable get(int value)
  {
    switch (value)
    {
      case CELL_VALUE: return CELL;
      case DOOR_VALUE: return DOOR;
      case EXIT_VALUE: return EXIT;
      case FIRE_VALUE: return FIRE;
      case PERSON_VALUE: return PERSON;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private Locatable(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //Locatable
