/**
 * generated by Xtext 2.16.0
 */
package org.xtext.bmod.ide;

import org.xtext.bmod.ide.AbstractBmodIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class BmodIdeModule extends AbstractBmodIdeModule {
}
