/**
 * generated by Xtext 2.16.0
 */
package org.xtext.bmod.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.bmod.BmodRuntimeModule;
import org.xtext.bmod.BmodStandaloneSetup;
import org.xtext.bmod.ide.BmodIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class BmodIdeSetup extends BmodStandaloneSetup {
  @Override
  public Injector createInjector() {
    BmodRuntimeModule _bmodRuntimeModule = new BmodRuntimeModule();
    BmodIdeModule _bmodIdeModule = new BmodIdeModule();
    return Guice.createInjector(Modules2.mixin(_bmodRuntimeModule, _bmodIdeModule));
  }
}
