/*
 * generated by Xtext 2.16.0
 */
package org.xtext.ha.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.ha.ui.internal.HaActivator;

public class RulesUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return HaActivator.getInstance().getInjector("org.xtext.ha.Rules");
	}

}
