/**
 * Generated by Xtext
 */
package org.xtext.ha.web.contentassist;

import org.xtext.ha.web.contentassist.AbstractRulesProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class RulesProposalProvider extends AbstractRulesProposalProvider {
}
