/*
 * generated by Xtext 2.16.0
 */
package org.xtext.bmod.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import org.xtext.bmod.BReactRuntimeModule
import org.xtext.bmod.BReactStandaloneSetup

/**
 * Initialization support for running Xtext languages as language servers.
 */
class BReactIdeSetup extends BReactStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new BReactRuntimeModule, new BReactIdeModule))
	}
	
}
